def PLUGIN_NAME = "sspl-plugin-mav"

environment {
    PLUGIN_NAME = "${PLUGIN_NAME}"
}

pipeline {
    agent {
        node {
            label 'sav-cppcheck'
            customWorkspace "${PLUGIN_NAME}/${BRANCH_NAME}"
        }
    }
    stages {
        stage('cppcheck') {
            steps {
                sh 'cppcheck -j2 --inline-suppr --std=c++11 --xml --xml-version=2 --enable=style --suppress=passedByValue -Imodules modules products 2> cppcheck.xml'
                sh 'cat cppcheck.xml'
                recordIssues tool: cppCheck(pattern: 'cppcheck.xml'), unstableTotalAll:1
            }
        }
    }
    post {
        always {
            emailext subject: 'TEST sending emails',
                body: 'Check console output at $BUILD_URL to view the results',
                recipientProviders: [
                    [$class: 'CulpritsRecipientProvider'],
                    [$class: 'DevelopersRecipientProvider'],
                    [$class: 'RequesterRecipientProvider']
                ],
                replyTo: 'ukdevvlx@sophos.com',
                to: 'douglas.leeder@sophos.com'
        }
        failure {
            emailext subject: 'cppcheck-style failed for SSPL-AV',
                body: 'Check console output at $BUILD_URL to view the results',
                recipientProviders: [
                    [$class: 'CulpritsRecipientProvider'],
                    [$class: 'DevelopersRecipientProvider'],
                    [$class: 'RequesterRecipientProvider']
                ],
                replyTo: 'ukdevvlx@sophos.com',
                to: 'douglas.leeder@sophos.com'
        }
    }
}
