*** Settings ***
Library     Process
Library     Collections
Library     OperatingSystem

Library     ${libs_directory}/LogUtils.py
Library     ${libs_directory}/FullInstallerUtils.py
Library     ${libs_directory}/CapnSubscriber.py
Library     ${libs_directory}/SshSupport.py
Library     ${libs_directory}/AuditSupport.py
Library     ${libs_directory}/OSUtils.py
Library     ${libs_directory}/UserUtils.py


Resource  ../sul_downloader/SulDownloaderResources.robot
Resource  ../installer/InstallerResources.robot
Resource  AuditPluginResources.robot
Resource  ../GeneralTeardownResource.robot

Test Setup  Run Keywords
...         Credential Tests Setup  AND
...         Require Fresh Install

Test Teardown  Run Keywords
...         General Test Teardown  AND
...         Credential Remove Test User and TearDown

Default Tags  AUDIT_PLUGIN  PUB_SUB  MANAGEMENT_AGENT


*** Test Cases ***

Credential Event is generated by Failed Ssh Session For Invalid User
    [Tags]  AUDIT_PLUGIN  PUB_SUB  EXCLUDE_AWS  MANAGEMENT_AGENT
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Failed Ssh Using Password   user=invalidUserName   password=anyone
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=(invalid user)  sessionType=networkInteractive   eventType=authFailure
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=(invalid user)  sessionType=networkInteractive   eventType=authFailure
    Check Network Address Is Set In Message Dictionary  ${message}


Credential Event is generated by Successful Ssh Session Using Password
    [Tags]  AUDIT_PLUGIN  PUB_SUB  EXCLUDE_AWS  MANAGEMENT_AGENT
    Add User For Test
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Successful Ssh Using Password   user=userfortest  password=linuxpassword
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    Check Network Address Is Set In Message Dictionary  ${message}


Credential Event is generated by Failed Ssh Session Using Invalid Password For Valid User
    [Tags]  AUDIT_PLUGIN  PUB_SUB  EXCLUDE_AWS  MANAGEMENT_AGENT
    Add User For Test
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Failed Ssh Using Password   user=userfortest  password=wrongpassword
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Successful Ssh Session Using Key
    Add User For Test
    Authorize Key Without Password   userfortest
    ${KeyWithoutPasswordPath}=  Create Private Key Without Password
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Successful Ssh Using Key and Password     user=userfortest  key_file_path=${KeyWithoutPasswordPath}  password=
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Failed Ssh Session Using Key
    Add User For Test
    Authorize Key With Password   userfortest
    ${KeyWithoutPasswordPath}=  Create Private Key Without Password
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Failed Ssh Using Key and Password     user=userfortest  key_file_path=${KeyWithoutPasswordPath}   password=
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Successful Ssh Session Using Password Followed by Invalid Key
    [Tags]  AUDIT_PLUGIN  PUB_SUB  EXCLUDE_AWS  MANAGEMENT_AGENT
    Add User For Test
    Authorize Key With Password   userfortest
    ${KeyWithoutPasswordPath}=  Create Private Key Without Password
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Successful Ssh Using Key and Password     user=userfortest  key_file_path=${KeyWithoutPasswordPath}   password=linuxpassword
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Successful Ssh Remote Command Execution Using Key
    Add User For Test
    Authorize Key Without Password   userfortest
    ${KeyWithoutPasswordPath}=  Create Private Key Without Password
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Successful Remote Command     user=userfortest     key_file_path=${KeyWithoutPasswordPath}
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authSuccess
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Failed Ssh Remote Command Execution Using Key
    Add User For Test
    Authorize Key Without Password   userfortest
    ${InvalidKey}=  Create Invalid Private Key
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Failed Remote Command     user=userfortest     key_file_path=${InvalidKey}
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    Check Network Address Is Set In Message Dictionary  ${message}

Credential Event is generated by Successful Ssh Remote Command Execution Using Password
    [Tags]  AUDIT_PLUGIN  PUB_SUB  EXCLUDE_AWS  MANAGEMENT_AGENT
    Add User For Test
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Successful Remote Command For Password     user=userfortest     password=linuxpassword
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  eventType=authSuccess  targetUserSID.username=userfortest  sessionType=networkInteractive
    ${message}=  Check Capn Output For A Single Message   ${channel}  eventType=authSuccess  targetUserSID.username=userfortest  sessionType=networkInteractive
    Check Network Address Is Set In Message Dictionary  ${message}


Credential Event is generated by Failed Ssh Remote Command Execution Using Password
    Add User For Test
    Install Audit Plugin Directly
    Start Subscriber
    Clear Auditd Logs
    Simulate Failed Remote Command For Password     user=userfortest     password=invalidpassword
    ${channel} =  Get Credential Channel
    Wait Until Keyword Succeeds
    ...  15 secs
    ...  1 secs
    ...  Clear Cache And Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    ${message}=  Check Capn Output For A Single Message   ${channel}  targetUserSID.username=userfortest  sessionType=networkInteractive  eventType=authFailure
    Check Network Address Is Set In Message Dictionary  ${message}

*** Keywords ***
Credential Tests Setup
    Setup Audit Plugin Collect Binary Data
    Ensure A Clean Start


Credential Tests TearDown
    Run Keyword If Test Failed  Store Binary Data  ${TEST NAME}.bin
    Default Test Teardown
    Clear Audit Plugin Collect Binary Data


Credential Remove Test User and TearDown
    Clear Private Keys
    Restore Authorized Keys  userfortest
    Delete User For Test
    Credential Tests TearDown

Check Network Address Is Set In Message Dictionary
    [Arguments]  ${message}
    ${remoteNetworkAddress}  Get From Dictionary  ${message}  remoteNetworkAddress.address
    ${length}=  Get Length  ${remoteNetworkAddress}
    Should Not Be Equal As Integers  ${length}  0  Network address is not set

