#!/bin/bash
set -ex

# This file is generated by the sdds build and it gets out of date and breaks builds, so just make sure it's removed.
rm sdds/sdds3/BUILD.bazel

#tap build linux_mono_repo.products.linux_rel_x86_64
exec tap build linux_mono_repo.products.sdds
