# Copyright 2023-2024 Sophos Limited. All rights reserved.

DEVICEISOLATION_LINE_ID = "ServerProtectionLinux-Plugin-DeviceIsolation"
DEVICEISOLATION_PLUGIN_NAME = "deviceisolation"
DEVICEISOLATION_PRODUCT_NAME = "SPL-Device-Isolation-Plugin"
DEVICEISOLATION_PRETTY_NAME = "Sophos Linux Device Isolation"

SUBSTITUTIONS = {
    "@PLUGIN_NAME@": DEVICEISOLATION_PLUGIN_NAME,
    "@PRODUCT_LINE_ID@": DEVICEISOLATION_LINE_ID,
    "@PRODUCT_PRETTY_NAME@": DEVICEISOLATION_PRETTY_NAME,
}
