# Copyright 2023 Sophos Limited. All rights reserved.
load(":version_info.bzl", "DEVICEISOLATION_BASE_VERSION", "DEVICEISOLATION_LINE_ID", "DEVICEISOLATION_PLUGIN_NAME", "DEVICEISOLATION_PRETTY_NAME")

SUBSTITUTIONS = {
    "@PLUGIN_NAME@": DEVICEISOLATION_PLUGIN_NAME,
    "@PLUGIN_VERSION@": DEVICEISOLATION_BASE_VERSION,
    "@PRODUCT_LINE_ID@": DEVICEISOLATION_LINE_ID,
    "@PRODUCT_PRETTY_NAME@": DEVICEISOLATION_PRETTY_NAME,
}
