filegroup(
    name = "make_sdds3_package",
    srcs = ["make-sdds3-package.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "make_sdds3_suites",
    srcs = ["make-sdds3-suites.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "make_sdds3_supplements_from_sdds2.py",
    srcs = ["make-sdds3-supplements-from-sdds2.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sdds3_builder_exe",
    srcs = ["sdds3-builder.exe"],
    visibility = ["//visibility:public"],
)
