name: Sync aws branch

on:
  push:
    branches:
      - develop

jobs:
  sync-branch:
    name: Update test branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: test/akis-test
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
