# Copyright 2023-2024 Sophos Limited. All rights reserved.

EVENTJOURNALER_LINE_ID = "ServerProtectionLinux-Plugin-EventJournaler"
EVENTJOURNALER_PLUGIN_NAME = "eventjournaler"
EVENTJOURNALER_PRODUCT_NAME = "SPL-Event-Journaler-Plugin"
EVENTJOURNALER_PRETTY_NAME = "Sophos Linux Event Journaler"

SUBSTITUTIONS = {
    "@PLUGIN_NAME@": EVENTJOURNALER_PLUGIN_NAME,
    "@PRODUCT_LINE_ID@": EVENTJOURNALER_LINE_ID,
    "@PRODUCT_PRETTY_NAME@": EVENTJOURNALER_PRETTY_NAME,
}
