#!/bin/bash

shopt -s nullglob

STARTINGDIR="$(pwd)"
SCRIPTDIR="${0%/*}"
if [[ "$SCRIPTDIR" == "$0" ]]
then
    SCRIPTDIR="${STARTINGDIR}"
fi

ABS_SCRIPTDIR=$(cd $SCRIPTDIR && pwd)
SOPHOS_INSTALL="${ABS_SCRIPTDIR%/bin*}"

base_version_file=${SOPHOS_INSTALL}/base/VERSION.ini


echo ""
echo "Version information for Sophos Linux Protection"
echo ""
if [[ -f ${base_version_file} ]]
then
	cat ${base_version_file}
fi

	echo ""

