%YAML 1.2
---
sus: ["linuxep"]
line-id: ServerProtectionLinux-Base
instances:
  - tags: ["RECOMMENDED", "BETA", "BETA2"]
    generate_static: True
    marketing_version: "{version} {sprint}"
    views:
      - platforms:
          - LINUX_INTEL_LIBC6
        component: BaseComponentSuite.latest
        subcomponents:
          base.latest.x64:
            supplements:
              - ssplflags
          event-journaler.latest.x64:
          liveresponse.latest.x64:
          responseactions.latest.x64:
          runtimedetections.latest.x64:
            supplements:
              - rdrules
          edr.latest.x64:
            supplements:
              - scheduledquerypack
              - scheduledquerypacknext
          av.latest.x64:
            supplements:
              - vdl
              - dataseta
              - mlmodel
      - platforms:
          - LINUX_ARM64
        component: BaseComponentSuite.latest
        subcomponents:
          base.latest.arm64:
            supplements:
              - ssplflags
          event-journaler.latest.arm64:
          liveresponse.latest.arm64:
          responseactions.latest.arm64:
          runtimedetections.latest.arm64:
            supplements:
              - rdrules
          edr.latest.arm64:
            supplements:
              - scheduledquerypack
              - scheduledquerypacknext
          av.latest.arm64:
            supplements:
              - vdl
              - dataseta
              - mlmodel
