import os
import json

from datetime import datetime
def get_run_time_from_file(filepath):
    content = []
    with open("./allresults/"+filepath, 'r') as f:
        content = f.readlines()
    starttime = ""
    for line in content:
        if "starttime" in line:
            starttime = line
            break

    endtime = ""
    for line in reversed(content):
        if "endtime" in line:
            endtime = line
            break
    start = extract_timestamp("starttime",starttime)
    end = extract_timestamp("endtime",endtime)
    FMT = '%H:%M:%S.%f'
    tdelta = datetime.strptime(end, FMT) - datetime.strptime(start, FMT)


    return round(tdelta.seconds/60)


def extract_timestamp(key, xml):
    timestamp = xml.split(key)[1].split("\"")[1][9:]
    return timestamp

def main():
    files = os.listdir("allresults")
    outputfiles = []
    for file in files:
        if "output.xml" in file:
            outputfiles.append(file)
    data = {}
    for file in outputfiles:
        key = file[:-11]
        index = key.find("load")
        loadtag = key[index:]
        time = get_run_time_from_file(file)
        try:
            count = data[loadtag]["count"]
            count = count + 1
            data[loadtag]["count"] = count
        except KeyError:
            data[loadtag] = {}
            data[loadtag]["count"] = 1


        data[loadtag][key] = time
    for loadtag in data:
        total = 0
        for machine in data[loadtag]:
            if machine != "count":
                total = total + data[loadtag][machine]
        data[loadtag]["average"] = round(total/data[loadtag]["count"], 1)

    with open("./report/data.json", 'w') as outfile:
            json.dump(data, outfile)

    tbl_body = "<table><tr> <th>Load ID</th> <span></span> <th>Average</th></tr>"
    for tag in data:
        tbl_row = "<td>"+tag+"</td>  </span><td>"+str(data[tag]["average"])+"</td>"
        tbl_body += "<tr>"+tbl_row+"</tr>"

        with open("./report/index.html", 'w') as outfile:
            outfile.write( 'This page is generated by a jenkins job <br>')
            outfile.write( 'JSON here: <a href="data.json">data.json</a>')
            outfile.write(tbl_body+"</table>")
main()