node('CentOSCloneBuilder') {
    dir('everest-base') {
        checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true, $class: 'LocalBranch', localBranch: "**"]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '541e91bb-1c10-4dd6-ae77-51fafda0f7c1', url: 'ssh://git@stash.sophos.net:7999/linuxep/everest-base.git']]]
    }
    dir('SSPL-AWS-Tests') {
        checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true, $class: 'LocalBranch', localBranch: "**"]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '541e91bb-1c10-4dd6-ae77-51fafda0f7c1', url: 'ssh://git@stash.sophos.net:7999/linuxep/sspl-aws-runner.git']]]
        sh 'sudo NO_CHECKOUT=1 ./run_tests_in_aws.sh'
        step(
            [$class: 'RobotPublisher',
            disableArchiveOutput: false,
            enableCache: true,
            logFileName: '*-log.html',
            onlyCritical: true,
            otherFiles: '',
            outputFileName: '*-output.xml',
            outputPath: './results',
            passThreshold: 100.0,
            reportFileName: '*-report.html',
            unstableThreshold: 80.0])
    }
}