pipeline {
    agent none
    stages {
        stage('Builds') {
            parallel {
                stage('Build on Ubuntu') {
                    agent { 
                        node {
                            label 'ubuntu1804'
                            customWorkspace "EverestBase/${BRANCH_NAME}"
                        }
                    }
                    steps {
                        checkout scm
                        mkdir build && cd build && cmake .. && make
                        ctest -V -T test && cp Testing/`head -n 1 Testing/TAG`/Test.xml ./CTestResults.xml
                    }
                    post {
                      always {
                        junit "build/CTestResults.xml"
                      }
                    }
                }
                stage('Build on CentOS') {
                    agent {
                        node {
                            label 'centos7'
                            customWorkspace "EverestBase/${BRANCH_NAME}"
                        }
                    }
                    steps {
                        checkout scm
                        mkdir build && cd build && cmake .. && make
                        ctest -V -T test && cp Testing/`head -n 1 Testing/TAG`/Test.xml ./CTestResults.xml
                    }
                    post {
                      always {
                        junit "build/CTestResults.xml"
                      }
                    }
                }
                stage('Build on Redhat') {
                    agent {
                        node {
                            label 'rhel7'
                            customWorkspace "EverestBase/${BRANCH_NAME}"
                        }
                    }
                    steps {
                        checkout scm
                        mkdir build && cd build && cmake .. && make
                        ctest -V -T test && cp Testing/`head -n 1 Testing/TAG`/Test.xml ./CTestResults.xml
                    }
                    post {
                      always {
                        junit "build/CTestResults.xml"
                      }
                    }
                }
            }
        }
    }
}
