
library "standardPipeline"

project = 'sspl-edr-plugin'
version_key = '1.0.2'
project_gitrepo = 'ssh://git@stash.sophos.net:7999/linuxep/sspl-plugin-edr-component.git'
project_builddir = 'sspl-edr-plugin-build'
project_release_xml = 'build-files/release-package.xml'
buildAgentTemplate = 'JenkinsLinuxTemplate1'

properties([
  parameters([
    string(name: 'CommitHash', defaultValue: ''),
    string(name: 'PortalId', defaultValue: ''),
    string(name: 'PortalAddress', defaultValue: ''),
    string(name: 'Mode', defaultValue: 'release'),
    string(name: 'UnitTest', defaultValue: 'yes')
  ])
])

skipDefaultCheckout()
try{
	version_number = GetVersionNumber(version_key, project)
    PreBuild(params.CommitHash, params.PortalId, params.PortalAddress)

    git_branch = "${env.BRANCH_NAME}"
    echo git_branch
    if (git_branch == 'feature/LINUXDAR-1278-move-bullseye-and-coverity-for-the-edr-plugin-to-ci-and-tap')
    {
        parallel Build:
        {
            echo 'Starting edr master release builds'
            ArtisanBuild(
                buildAgentTemplate,
                project_release_xml,
                params.Mode,
                version_number,
                project_builddir)
            echo 'Finished edr master release build'
        },
        //TODO - uncomment this when CI supports bullseye
        coverage_build:
        {
            echo 'Starting edr master coverage build'
            ArtisanBuild(
                'JenkinsLinuxTemplate3',
                project_release_xml,
                'coverage',
                version_number,
                project_builddir)
            echo 'Finished edr master coverage build'
        },
        coverity_build:
        {
            echo 'Starting edr master coverage build'
            ArtisanBuild(
                'JenkinsLinuxTemplate3',
                project_release_xml,
                'coverity',
                version_number,
                project_builddir)
            echo 'Finished edr master coverage build'
        }
    }
    else
    {
        echo 'Starting ticket branch edr build'
        ArtisanBuild(buildAgentTemplate, project_release_xml, params.Mode, version_number, project_builddir)
    }
    SuccessfulBuild(project_release_xml)

} catch(e){
    FailedBuild(params.CommitHash, params.PortalId, params.PortalAddress)
    error("Build failed: " + e.toString())
}
