environment {
    PLUGIN_NAME = "TemplatePlugin"
}

def buildUsingScript()
{
    checkout scm
    withEnv(['PATH+CMAKE=/build/input/gcc/bin:/build/input/cmake/bin:/usr/local/bin']) {
        sh './build.sh'
    }
}

def copyOutputToFiler(PLUGIN_NAME)
{
    sh "sudo rm -rf /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
    sh "sudo mkdir -p /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
    sh "sudo cp -r output/* /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
}

pipeline {
    agent none
    stages {
        stage('Build on Centos Build Machine') {
            agent {
                node {
                    label 'centos-jenkins-builder'
                    customWorkspace "${PLUGIN_NAME}/${BRANCH_NAME}"
                }
            }
            steps {
                buildUsingScript()
            }
            post {
                success {
                    copyOutputToFiler(${PLUGIN_NAME})
                }
            }
        }
    }
}