def PLUGIN_NAME = "sspl-template-plugin"

environment {
    PLUGIN_NAME = "${PLUGIN_NAME}"
}

def buildUsingScript(PLUGIN_NAME)
{
    checkout scm
    withEnv(['PATH+CMAKE=/build/input/gcc/bin:/build/input/cmake/bin:/usr/local/bin']) {
        sh "./build.sh --name ${PLUGIN_NAME}"
    }
}

def copyOutputToFiler(PLUGIN_NAME)
{
    sh "sudo rm -rf /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
    sh "sudo mkdir -p /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
    sh "sudo rsync -rtp output/* /mnt/filer6/linux/SSPL/JenkinsBuildOutput/${PLUGIN_NAME}/${BRANCH_NAME}"
}

pipeline {
    agent none
    stages {
        stage('Build on Centos Build Machine') {
            agent {
                node {
                    label 'centos-jenkins-builder'
                    customWorkspace "${PLUGIN_NAME}/${BRANCH_NAME}"
                }
            }
            steps {
                buildUsingScript("${PLUGIN_NAME}")
            }
            post {
                success {
                    copyOutputToFiler("${PLUGIN_NAME}")
                }
            }
        }
    }
}