# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PluginAPIMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PluginAPIMessage.proto',
  package='PluginProtocolProto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16PluginAPIMessage.proto\x12\x13PluginProtocolProto\"\xaa\x03\n\x10PluginAPIMessage\x12\x12\n\npluginName\x18\x01 \x01(\t\x12\x44\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x33.PluginProtocolProto.PluginAPIMessage.CommandOption\x12\x15\n\rapplicationId\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x03(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63knowledge\x18\x06 \x01(\x08\x12\x15\n\rcorrelationId\x18\x07 \x01(\t\"\xd8\x01\n\rCommandOption\x12\r\n\tSendEvent\x10\x01\x12\x0e\n\nSendStatus\x10\x02\x12\x10\n\x0cRegistration\x10\x03\x12\x0f\n\x0b\x41pplyPolicy\x10\x04\x12\x0c\n\x08\x44oAction\x10\x05\x12\x11\n\rRequestStatus\x10\x06\x12\r\n\tTelemetry\x10\x07\x12\x18\n\x14RequestCurrentPolicy\x10\x08\x12\x12\n\x0eInvalidCommand\x10\t\x12\x11\n\rRequestHealth\x10\n\x12\x14\n\x10SendThreatHealth\x10\x0b'
)



_PLUGINAPIMESSAGE_COMMANDOPTION = _descriptor.EnumDescriptor(
  name='CommandOption',
  full_name='PluginProtocolProto.PluginAPIMessage.CommandOption',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SendEvent', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SendStatus', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Registration', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ApplyPolicy', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DoAction', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RequestStatus', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Telemetry', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RequestCurrentPolicy', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidCommand', index=8, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RequestHealth', index=9, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SendThreatHealth', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=258,
  serialized_end=474,
)
_sym_db.RegisterEnumDescriptor(_PLUGINAPIMESSAGE_COMMANDOPTION)


_PLUGINAPIMESSAGE = _descriptor.Descriptor(
  name='PluginAPIMessage',
  full_name='PluginProtocolProto.PluginAPIMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pluginName', full_name='PluginProtocolProto.PluginAPIMessage.pluginName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='PluginProtocolProto.PluginAPIMessage.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applicationId', full_name='PluginProtocolProto.PluginAPIMessage.applicationId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PluginProtocolProto.PluginAPIMessage.payload', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='PluginProtocolProto.PluginAPIMessage.error', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acknowledge', full_name='PluginProtocolProto.PluginAPIMessage.acknowledge', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlationId', full_name='PluginProtocolProto.PluginAPIMessage.correlationId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLUGINAPIMESSAGE_COMMANDOPTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=474,
)

_PLUGINAPIMESSAGE.fields_by_name['command'].enum_type = _PLUGINAPIMESSAGE_COMMANDOPTION
_PLUGINAPIMESSAGE_COMMANDOPTION.containing_type = _PLUGINAPIMESSAGE
DESCRIPTOR.message_types_by_name['PluginAPIMessage'] = _PLUGINAPIMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PluginAPIMessage = _reflection.GeneratedProtocolMessageType('PluginAPIMessage', (_message.Message,), {
  'DESCRIPTOR' : _PLUGINAPIMESSAGE,
  '__module__' : 'PluginAPIMessage_pb2'
  # @@protoc_insertion_point(class_scope:PluginProtocolProto.PluginAPIMessage)
  })
_sym_db.RegisterMessage(PluginAPIMessage)


# @@protoc_insertion_point(module_scope)
