# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'socket'

hostname = Socket.gethostname

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.define "ubuntu", primary: true do |ubuntu|
        ubuntu.vm.box = "ubuntu-bionic"
        ubuntu.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/ubuntu-bionic-bento.box"
        ubuntu.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        config.vm.provision "file", source: __dir__+"/everest-base/testUtils/SupportFiles/jenkins/auditdConfig.txt", destination: "/home/vagrant/auditdConfig.txt"
        ubuntu.vm.provision :shell, path: "bootstrap_ubuntu.sh"
        ubuntu.vm.provision :shell, path: "bootstrap_common.sh"
        config.vm.hostname = "vagrant#{hostname}"
    end

    config.vm.define "centos" do |centos|
        centos.vm.box = "centos-7"
        centos.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/centos-7.box"

        centos.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        config.vm.provision "file", source: __dir__+"/everest-base/testUtils/SupportFiles/jenkins/auditdConfig.txt", destination: "/home/vagrant/auditdConfig.txt"
        centos.vm.provision :shell, path: "bootstrap_centos.sh"
        centos.vm.provision :shell, path: "bootstrap_common.sh"

    end

    config.vm.define "rhel" do |rhel|
        rhel.vm.box = "rhel-7-5"
        rhel.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/RHEL-7-5.box"

        rhel.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        config.vm.provision "file", source: __dir__+"/everest-base/testUtils/SupportFiles/jenkins/auditdConfig.txt", destination: "/home/vagrant/auditdConfig.txt"
        rhel.vm.provision :shell, path: "bootstrap_rhel.sh"
        rhel.vm.provision :shell, path: "bootstrap_common.sh"
    end


end
