# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'socket'

hostname = Socket.gethostname

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.define "ubuntu", primary: true do |ubuntu|
        ubuntu.vm.box = "ubuntu-bionic"
        ubuntu.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/ubuntu-bionic-bento.box"
        ubuntu.vm.network "forwarded_port", guest: 9000, host: 9000
        ubuntu.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        ubuntu.vm.provision :shell, path: "bootstrap_ubuntu.sh"
        ubuntu.vm.provision :shell, path: "bootstrap_common.sh"
    end

    config.vm.define "centos" do |centos|
        centos.vm.box = "centos-7"
        centos.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/centos-7.box"

        centos.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        centos.vm.provision :shell, path: "bootstrap_common.sh"

    end

    config.vm.define "rhel" do |rhel|
        rhel.vm.box = "rhel-7-5"
        rhel.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/RHEL-7-5.box"

        rhel.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
        rhel.vm.provision :shell, path: "bootstrap_rhel.sh"
        rhel.vm.provision :shell, path: "bootstrap_common.sh"
    end

    require 'vagrant-aws'
    config.vm.define "amazon_linux" do |amazon_linux|
        amazon_linux.vm.box = 'amazon_linux_2'
        amazon_linux.vm.box_url = "file:///mnt/filer6/linux/ISOs/Vagrant_Boxes/amazon-linux-2.box"
        amazon_linux.vm.provider 'aws' do |aws, override|
            aws.keypair_name = 'regressiontesting'
            aws.instance_type = 't2.micro'
            aws.region = 'eu-west-1'
            aws.ami = 'ami-0f913bec34ae13118'
            aws.security_groups = ['SSH-FROM-SOPHOS']
            override.ssh.username = 'ec2-user'
            override.ssh.private_key_path = 'ssh-keys/regressiontesting.pem'
            override.nfs.functional = false
            aws.tags = {
                Name: "Vagrant Amazon Linux 2 for #{hostname}",
                Owner: 'ukdevsavlinux',
                SupportEmail: 'ukdevsavlinux@sophos.com',
                BusinessUnit: 'esg',
                CostCentre: 'GB11601200',
                Project: 'SAV',
                Application: 'Manual',
                Environment: 'development',
                AutomationExcluded: 'true',
                SecurityClassification: 'none low',
                DevBox: "#{hostname}"
            }
        end

        #aws doesn't rsync the root of sspl-tools. Therefore we need to use a file provisioner to scp auditdConfig.txt to /home/ec2-user/auditdConfig.txt (cant copy directly to /vagrant/auditdConfig.txt due to permissions)
        config.vm.provision "file", source: "./auditdConfig.txt", destination: "/home/ec2-user/auditdConfig.txt"

        amazon_linux.vm.provision :shell, path: "bootstrap_amazon_linux.sh"
        amazon_linux.vm.provision :shell, path: "bootstrap_common.sh"

        # By default vagrant will rsync everything in root folder.
        # the line below will prevent this.  This is to ensure we do not upload source code to AWS.
        amazon_linux.vm.synced_folder '.', '/vagrant', disabled: true

    end

end