#!/bin/bash

set -e

THIS_SCRIPT=$(readlink -f ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

cd "$SCRIPT_DIR"
source "$SCRIPT_DIR/vagrant_env_vars.sh"

# There is a bug with virtual box where the main UI has to be open during boot else booting hangs.
if [[ "$@" == *"up"* || "$@" == *"reload"* ]]; then
  pgrep VirtualBox.exe &> /dev/null || "/mnt/c/Program Files/Oracle/VirtualBox/VirtualBox.exe" &
fi

vagrant "$@"


