function(FindLibraryFullPath FULLPATH LIBNAME LIBRARY_PATH)
    set(FOUND_LIB ${LIBNAME}-NOTFOUND)
    FIND_LIBRARY(FOUND_LIB
            NAMES ${LIBNAME}
            PATHS ${LIBRARY_PATH}
            NO_DEFAULT_PATH
            )
    GET_FILENAME_COMPONENT(FOUND_LIB_ABSOLUTE ${FOUND_LIB} REALPATH)
    set(${FULLPATH} ${FOUND_LIB_ABSOLUTE} PARENT_SCOPE)
endfunction(FindLibraryFullPath)