
library "standardPipeline"

project = 'sspl-thininstaller'
version = '1.0.4'
project_gitrepo = 'ssh://git@stash.sophos.net:7999/linuxep/thininstaller.git'
project_builddir = 'sspl-thininstaller-build'
project_release_xml = 'release-package.xml'

properties([
  parameters([
    string(name: 'CommitHash', defaultValue: ''),
    string(name: 'PortalId', defaultValue: ''),
    string(name: 'PortalAddress', defaultValue: '')
  ])
])

skipDefaultCheckout()
try{
	version_number = GetVersionNumber(version, project)
    PreBuild(params.CommitHash, params.PortalId, params.PortalAddress)

    parallel Build:{
        ArtisanBuild(
            params.CommitHash,
            params.PortalId,
            'Release',
            project_builddir,
            project_release_xml,
            'JenkinsLinuxTemplate1',
			version_number,
            'develop',
            project_gitrepo,
            "${env.BRANCH_NAME}",
            'release')
        }

    SuccessfulBuild(
		params.CommitHash,
		params.PortalId,
		params.PortalAddress,
		'develop',
		project_gitrepo,
		"${env.BRANCH_NAME}",
		project_release_xml)

} catch(e){
    FailedBuild(params.CommitHash, params.PortalId, params.PortalAddress)
    error("Build failed: " + e.toString())
}
