# Copyright 2023 Sophos Limited. All rights reserved.
load(":version_info.bzl", "EVENTJOURNALER_LINE_ID", "EVENTJOURNALER_PLUGIN_NAME", "EVENTJOURNALER_PRETTY_NAME", "EVENTJOURNALER_VERSION")

SUBSTITUTIONS = {
    "@PLUGIN_NAME@": EVENTJOURNALER_PLUGIN_NAME,
    "@PLUGIN_VERSION@": EVENTJOURNALER_VERSION,
    "@PRODUCT_LINE_ID@": EVENTJOURNALER_LINE_ID,
    "@PRODUCT_PRETTY_NAME@": EVENTJOURNALER_PRETTY_NAME,
}
