load("//tools/config:pylint.bzl", "pylint")

py_binary(
    name = "env",
    srcs = ["env.py"],
    python_version = "PY3",
    visibility = ["//sdds3:__pkg__"],
)

filegroup(
    name = "maker",
    srcs = ["maker.py"],
    visibility = ["//sdds3:__pkg__"],
)

